version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - kiutra

  init_db:
    build:
      context: ./server
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
    command: sh -c "sleep 10 && python table.py" # Add a delay of 10 seconds before running table.py
    networks:
      - kiutra

  server:
    build:
      context: ./server
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
    # depends_on:
    #   - init_db
    # command: sh -c "sleep 15 && python server.py" # Add a delay of 15 seconds before running backend_server.py
    networks:
      - kiutra

  backend:
    build:
      context: .
      dockerfile: ./backend_server/Dockerfile
    volumes:
      - plots-data:/app/plots
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
    # depends_on:
    #   - init_db
    #command: sh -c "sleep 20 && python backend_server.py" # Add a delay of 20 seconds before running backend_server.py
    networks:
      - kiutra

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - plots-data:/app/plots
    ports:
      - "5001:5001"
    environment:
      - BACKEND_URL=http://backend:5000/api/processed-data
    networks:
      - kiutra
volumes:
  plots-data:
networks:
  kiutra:
    external: true
