version: "3"
services:
  server:
    build:
      context: ./server
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
    networks:
      - my_network

  backend:
    build:
      context: ./backend_server
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
    networks:
      - my_network

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000/api/processed-data
    networks:
      - my_network

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    external: true
